---
- name: Disable root login.
  become: yes
  lineinfile:
    line: 'PermitRootLogin no'
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin .*'
    state: present
  when: bootstrap_disable_root_login
  tags: ['lineinfile', 'security', 'sshd']
  notify: sshd-restarted-handler
