---
- name: Install postfix and related packages.
  package:
    name: "{{ item }}"
    state: present
  tags: ['package', 'smtp']
  with_items:
    - cyrus-sasl-plain
    - postfix

- name: Setup SASL credentials.
  template:
    dest: /etc/postfix/sasl_passwd
    group: root
    mode: 0644
    owner: root
    src: postfix/sasl_passwd.j2
    validate: postmap %s
  tags: ['template', 'smtp']

- name: Check if SASL credentials db file exists.
  stat:
    path: /etc/postfix/sasl_passwd.db
  register: stat_sasl_passwd

- name: Create SASL credentials db.
  shell: postmap /etc/postfix/sasl_passwd
  tags: ['shell']
  when: stat_sasl_passwd.stat.exists == false

- name: Set config for relayhost.
  lineinfile:
    line: 'relayhost = [{{bootstrap_smtp_host}}]:{{bootstrap_smtp_port}}'
    dest: /etc/postfix/main.cf
    regexp: '^#?relayhost(.*)$'
    state: present
  tags: ['lineinfile', 'smtp', 'sasl']
  notify: postfix-restarted-handler

- name: Set config for smtp_sasl_auth_enable.
  lineinfile:
    line: 'smtp_sasl_auth_enable = yes'
    dest: /etc/postfix/main.cf
    regexp: '^#?smtp_sasl_auth_enable(.*)$'
    state: present
  tags: ['lineinfile', 'smtp', 'sasl']
  notify: postfix-restarted-handler

- name: Set config for smtp_sasl_security_options.
  lineinfile:
    line: 'smtp_sasl_security_options = noanonymous'
    dest: /etc/postfix/main.cf
    regexp: '^#?smtp_sasl_security_options(.*)$'
    state: present
  tags: ['lineinfile', 'smtp', 'sasl']
  notify: postfix-restarted-handler

- name: Set config for smtp_sasl_password_maps.
  lineinfile:
    line: 'smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd'
    dest: /etc/postfix/main.cf
    regexp: '^#?smtp_sasl_password_maps(.*)$'
    state: present
  tags: ['lineinfile', 'smtp', 'sasl']
  notify: postfix-restarted-handler

- name: Set config for smtp_use_tls.
  lineinfile:
    line: 'smtp_use_tls = yes'
    dest: /etc/postfix/main.cf
    regexp: '^#?smtp_use_tls(.*)$'
    state: present
  tags: ['lineinfile', 'smtp', 'sasl']
  notify: postfix-restarted-handler

- name: Set config for smtp_tls_security_level.
  lineinfile:
    line: 'smtp_tls_security_level = encrypt'
    dest: /etc/postfix/main.cf
    regexp: '^#?smtp_tls_security_level(.*)$'
    state: present
  tags: ['lineinfile', 'smtp', 'sasl']
  notify: postfix-restarted-handler

- name: Set config for smtp_tls_note_starttls_offer.
  lineinfile:
    line: 'smtp_tls_note_starttls_offer = yes'
    dest: /etc/postfix/main.cf
    regexp: '^#?smtp_tls_note_starttls_offer(.*)$'
    state: present
  tags: ['lineinfile', 'smtp', 'sasl']
  notify: postfix-restarted-handler

- name: Set config for smtp_fallback_relay.
  lineinfile:
    line: '#-o smtp_fallback_relay='
    dest: /etc/postfix/main.cf
    regexp: '-o smtp_fallback_relay='
    state: present
  tags: ['lineinfile', 'smtp', 'sasl']
  notify: postfix-restarted-handler

- name: Set config for virtual_alias_maps.
  lineinfile:
    line: 'virtual_alias_maps = regexp:/etc/postfix/virtual'
    dest: /etc/postfix/main.cf
    regexp: '^#?virtual_alias_maps(.*)$'
    state: present
  tags: ['lineinfile', 'smtp']
  when: bootstrap_smtp_rewrite_all
  notify: postfix-restarted-handler

- name: Set config for virtual_alias_domains.
  lineinfile:
    line: 'virtual_alias_domains ='
    dest: /etc/postfix/main.cf
    regexp: '^#?virtual_alias_domains =$'
    state: present
  tags: ['lineinfile', 'smtp']
  when: bootstrap_smtp_rewrite_all
  notify: postfix-restarted-handler

- name: Setup virtual_alias_maps file.
  template:
    dest: /etc/postfix/virtual
    group: root
    mode: 0644
    owner: root
    src: postfix/virtual.j2
  tags: ['template', 'smtp']
  when: bootstrap_smtp_rewrite_all
  notify: postfix-restarted-handler
