---
- name: Disable root login.
  lineinfile:
    line: 'PermitRootLogin no'
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin yes'
    state: present
  when: bootstrap_disable_root_login
  tags: ['lineinfile', 'security', 'sshd']